---
- hosts: all
  become: yes
  tasks:
    - name: install java, tree ,wget in all nodes
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - default-jdk
        - tree
        - wget
